## Producer service JSON-RPC APIs

Producer default endpoint: `http://localhost:5530`

*HTTP POST request format for all APIs*

[source]
----
{
    "method": "_call",
    "params": {
        "call_id": "api_call",
        "api_id": <API_ID: str>,
        "api_params": <API_PARAMS: dict>
    },
    "id": <REQUEST_ID: int>,
  	"jsonrpc": "2.0"
}
----

*Example*

Call `last_block_height` of transform `stake_history`
[source]
----
{
    "method": "_call",
    "params": {
        "call_id": "api_call",
        "api_id": "last_block_height",
        "api_params": {"transform_id": "stake_history"}
    },
    "id": 123,
  	"jsonrpc": "2.0"
}
----

## API Reference

_For convenience, API reference contains only_ `api_id` _and_ `api_params`

### Zone `public-icon`

List of `TRANSFORM_ID`:
[source]
----
stake_history
stake_top100
----

*last_block_height*

Ask for the last block height value of latest aggregated block of one specific transform
[source]
----
"api_id": "last_block_height"

"api_params": {"transform_id": <TRANSFORM_ID: str>}
----

*get_staking_info_last_block*

Basic stake metrics of the chain at latest block
[source]
----
"api_id": "get_staking_info_last_block"
----

*get_staking_info*

Basic stake metrics of the chain at one specific block in the past
[source]
----
"api_id": "get_staking_info"

"api_params": {"height": <BLOCK_HEIGHT: int>}
----

*latest_unstake_state*

List of wallets being in unlock period ( unstaking )
[source]
----
"api_id": "latest_unstake_state"
----

*latest_stake_top100*

Latest list of top100 staking wallets
[source]
----
"api_id": "latest_stake_top100"
----

*recent_stake_wallets*

List of recently stake wallets, ordered by block height
[source]
----
"api_id": "recent_stake_wallets"
----

*abstention_stake*

Latest list of wallets that already staked but not voting all staked ICX
[source]
----
"api_id": "abstention_stake"
----